### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Kaabero** [RedFoxFinn/ot-harjoitustyo#1]
**Päivämäärä ja kellonaika:** 

- Koodi ladattu 13.12. klo 8. 

**Ohjelman käyttö:**

-	Kiva idea projektin aiheeksi :)
-	Käyttöohjeisiin/releaseihin olisi hyvä lisätä, millä komennoilla ohjelma käynnistetään
-	Hieno ja toimiva grafiikka
-	Ohjelman käyttö selkeää ja loogista
-	Kun klikataan Näytä tuotteet ja listaus -näkymä avautuu, voisi tässä olla vielä otsikot sarakkeiden yläpuolella
-	Jos tuotteen lisää valitsematta tyyppiä, Näytä tuotteet -näkymä ei enää avaudu ja ohjelma jää jumiin. 

	-> TypeError: expected string or bytes-like object, got 'NoneType'
	-> Tuotteiden tarkastelu ei toimi uudelleenkäynnistyksenkään jälkeen
	-> Olisiko tyypin valitsemisen hyvä olla pakollista, lisäys ei onnistuisi ilman tyypin valitsemista?

**Koodi:**

-	Pantry.py -tiedoston ja services- sekä tools -hakemistojen tiedostot: selkeää koodia ja helppo ymmärtää, mitä mikäkin luokka ja metodi tekee
-	Hyvä koodin docstring -dokumentointi läpi koko ohjelman (vaikkakin englantia ja suomea sekaisin). Dokumentointi auttaa tässä selkeästi koodikokonaisuuden ymmärtämistä.
-	Helposti korjattavia pylint -huomautuksia aika paljon, kannattaa käydä läpi ja korjata helpot
-	Testit oleellisia ja menevät läpi
-	Ui -hakemistossa, joitakin metodeja, jotka vaikeaselkoisia. Mietin, voisiko näitä toteuttaa toisin/siivota jollain tavalla:
	- list_product.py: update()
	- add_product.py: _initialize()
	- stats.py: update()

**Comment by RedFoxFinn** [comment]
Oikein hyviä pointteja, kiitokset. Tuossa meni jotain juuri rikki kesken viime viikon ja harmillisesti se sitten tuli katselmointiin mukaan (illemmalla olin jo korjaillut ja höyryt nousten kirjoitellut lisää testejä.
